/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: fe0318d6348123b32ab662e99b9e01f9)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SlideDeckAgent";
  }
  interface Env {
    LOADER: WorkerLoader;
    AI: Ai;
    SlideDeckAgent: DurableObjectNamespace<
      import("./src/server").SlideDeckAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
