/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts`
interface __BaseEnv_Env {
  ATTACHMENTS: R2Bucket;
  SLAM: DurableObjectNamespace<import("./src/index").SlamSession>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "SlamSession";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
