/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: e1991039664e15ede8d9f82da6a31b78)
interface __BaseEnv_Env {
  AI: Ai;
  SkillsAgent: DurableObjectNamespace<import("./src/server").SkillsAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SkillsAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
