/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: b21f6462e8deced23ba596e48bd84127)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  MODEL: "@cf/moonshotai/kimi-k2.7-code";
  MAX_STEPS: "12";
  MAX_RLM_DEPTH: "1";
  MAX_RLM_CALLS: "8";
  TURN_TIMEOUT_MS: "180000";
  API_TOKEN: string;
  RlmThinkAgent: DurableObjectNamespace<import("./src/server").RlmThinkAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "RlmThinkAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "MODEL"
      | "MAX_STEPS"
      | "MAX_RLM_DEPTH"
      | "MAX_RLM_CALLS"
      | "TURN_TIMEOUT_MS"
      | "API_TOKEN"
    >
  > {}
}
