/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 39b6cc56bfd5c181db78d47092049a2a)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MemoryAgent";
  }
  interface Env {
    OPENAI_API_KEY: string;
    AGENT: DurableObjectNamespace<import("./src/server").MemoryAgent>;
    AI: Ai;
  }
}
interface Env extends Cloudflare.Env {}
