/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 0bcceb4ca8cdb86b80ff52de75d3292b)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MemoryAgent";
  }
  interface Env {
    AGENT: DurableObjectNamespace<import("./src/server").MemoryAgent>;
    AI: Ai;
  }
}
interface Env extends Cloudflare.Env {}
