/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b86a942499b71688673375629d931c79)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ReminderAgent";
  }
  interface Env {
    ReminderAgent: DurableObjectNamespace<import("./src/server").ReminderAgent>;
    VAPID_PUBLIC_KEY: string;
    VAPID_PRIVATE_KEY: string;
    VAPID_SUBJECT: string;
  }
}
interface Env extends Cloudflare.Env {}
