/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 823b3ba69b0ebf20f9bf8e5f9e27db5a)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "AgentThread";
  }
  interface Env {
    AGENT_THREAD: DurableObjectNamespace<import("./src/index").AgentThread>;
  }
}
interface Env extends Cloudflare.Env {}
