/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyAssistant";
  }
  interface Env {
    AI: Ai;
    MyAssistant: DurableObjectNamespace<import("./src/server").MyAssistant>;
  }
}
interface Env extends Cloudflare.Env {}
