/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 2b0c06b546741fc31b1d905640fbe299)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  AssistantDirectory: DurableObjectNamespace /* ThinkAgent_Assistant */;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET">
  > {}
}
