/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 3ba9c893cec3f3e64650c6bdd4c68a76)
interface __BaseEnv_Env {
  TaskEventsAgent: DurableObjectNamespace<
    import("./src/server").TaskEventsAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "TaskEventsAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
