/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: fc723635e466c66a5e988445010200e7)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Think";
  }
  interface Env {
    LOADER: WorkerLoader;
    BROWSER: Fetcher;
    ASSETS: Fetcher;
    OPENAI_API_KEY: string;
    BRAVE_API_KEY: string;
    Think: DurableObjectNamespace<import("./src/server").Think>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY" | "BRAVE_API_KEY">
  > {}
}
