/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: f4628205e3326b6aefbda1d54b36407a)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Coder";
  }
  interface Env {
    LOADER: WorkerLoader;
    BROWSER: Fetcher;
    OPENAI_API_KEY: string;
    BRAVE_API_KEY: string;
    Coder: DurableObjectNamespace<import("./src/server").Coder>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY" | "BRAVE_API_KEY">
  > {}
}
