/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 9765a6e30b45613c702ee08274f4d7e7)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SyncBot";
  }
  interface Env {
    AI: Ai;
    SLACK_BOT_TOKEN: string;
    SLACK_SIGNING_SECRET: string;
    TELEGRAM_BOT_TOKEN: string;
    SyncBot: DurableObjectNamespace<import("./src/server").SyncBot>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "SLACK_BOT_TOKEN" | "SLACK_SIGNING_SECRET" | "TELEGRAM_BOT_TOKEN"
    >
  > {}
}
