/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: ccfc130f4569a17cafb4334d811807df)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "VoiceAgent";
  }
  interface Env {
    AI: Ai;
    VoiceAgent: DurableObjectNamespace<import("./src/server").VoiceAgent>;
  }
}
interface Env extends Cloudflare.Env {}
