/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: cf4398cc35a32c23927f529675633d1f)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "VoiceAgent";
  }
  interface Env {
    AI: Ai;
    ELEVENLABS_API_KEY: string;
    DEEPGRAM_API_KEY: string;
    VoiceAgent: DurableObjectNamespace<import("./src/server").VoiceAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ELEVENLABS_API_KEY" | "DEEPGRAM_API_KEY">
  > {}
}
