/**
 * Run Think's workers suite against the harness-backed Think and keep score.
 *
 *   pnpm test:harness          run everything, rewrite harness-compat.{md,json}
 *   pnpm test:harness --check  run everything, fail if a test that passed in
 *                              harness-compat.json fails now
 *
 * The denominator is every test the normal suite collects, so a file that
 * fails to load under the harness counts all its tests as failing.
 */
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

type ListedTest = { name: string; file: string };
type AssertionResult = {
  ancestorTitles: string[];
  title: string;
  status: string;
};
type RunReport = {
  testResults: Array<{ name: string; assertionResults: AssertionResult[] }>;
};
type Scoreboard = {
  total: number;
  passed: number;
  files: Record<string, { total: number; passed: number }>;
  passing: string[];
};

const packageDir = path.join(import.meta.dirname, "..");
const scoreboardJson = path.join(packageDir, "harness-compat.json");
const scoreboardMd = path.join(packageDir, "harness-compat.md");
const check = process.argv.includes("--check");
const work = mkdtempSync(path.join(tmpdir(), "think-harness-"));

function vitest(args: string[]): void {
  spawnSync("pnpm", ["exec", "vitest", ...args], {
    cwd: packageDir,
    stdio: ["ignore", "inherit", "inherit"]
  });
}

function relative(file: string): string {
  return path.relative(path.join(packageDir, "src", "tests"), file);
}

function id(file: string, name: string): string {
  return `${relative(file)} > ${name}`;
}

// 1. Every test the normal suite has.
const inventoryFile = path.join(work, "inventory.json");
vitest(["list", "-c", "src/tests/vitest.config.ts", `--json=${inventoryFile}`]);
if (!existsSync(inventoryFile)) {
  console.error("Could not list the Think test suite.");
  process.exit(1);
}
const inventory = JSON.parse(
  readFileSync(inventoryFile, "utf8")
) as ListedTest[];

// 2. The same suite against the harness-backed Think.
const reportFile = path.join(work, "report.json");
vitest([
  "--run",
  "-c",
  "src/tests/vitest.harness.config.ts",
  "--reporter=dot",
  "--reporter=json",
  `--outputFile.json=${reportFile}`
]);
const report = existsSync(reportFile)
  ? (JSON.parse(readFileSync(reportFile, "utf8")) as RunReport)
  : { testResults: [] };

const passedIds = new Set<string>();
for (const file of report.testResults) {
  for (const test of file.assertionResults) {
    if (test.status !== "passed") continue;
    passedIds.add(
      id(file.name, [...test.ancestorTitles, test.title].join(" > "))
    );
  }
}

// 3. Score against the inventory.
const files: Scoreboard["files"] = {};
const passing: string[] = [];
for (const test of inventory) {
  const key = relative(test.file);
  const testId = id(test.file, test.name);
  files[key] ??= { total: 0, passed: 0 };
  files[key].total += 1;
  if (passedIds.has(testId)) {
    files[key].passed += 1;
    passing.push(testId);
  }
}
passing.sort();
const scoreboard: Scoreboard = {
  total: inventory.length,
  passed: passing.length,
  files: Object.fromEntries(
    Object.entries(files).sort(([a], [b]) => a.localeCompare(b))
  ),
  passing
};

const percent = (passed: number, total: number) =>
  total === 0 ? "0%" : `${Math.floor((passed / total) * 100)}%`;
console.log(
  `\nThink on ThinkHarness: ${scoreboard.passed} of ${scoreboard.total} tests pass (${percent(scoreboard.passed, scoreboard.total)}).`
);

if (check) {
  const recorded = existsSync(scoreboardJson)
    ? (JSON.parse(readFileSync(scoreboardJson, "utf8")) as Scoreboard)
    : { passing: [] as string[] };
  const now = new Set(passing);
  const regressions = recorded.passing.filter((test) => !now.has(test));
  const recordedSet = new Set(recorded.passing);
  const gains = passing.filter((test) => !recordedSet.has(test));
  if (gains.length > 0) {
    console.log(
      `${gains.length} more tests pass than harness-compat.json records. Run pnpm test:harness to record them.`
    );
  }
  if (regressions.length > 0) {
    console.error(`\n${regressions.length} tests that passed now fail:`);
    for (const test of regressions) console.error(`  ${test}`);
    process.exit(1);
  }
  process.exit(0);
}

writeFileSync(scoreboardJson, `${JSON.stringify(scoreboard, null, 2)}\n`);
const rows = Object.entries(scoreboard.files).map(
  ([file, { total, passed }]) =>
    `| \`${file}\` | ${passed} / ${total} | ${percent(passed, total)} |`
);
writeFileSync(
  scoreboardMd,
  `# Think on ThinkHarness

Generated by \`pnpm test:harness\`. Do not edit by hand.

Think's workers suite, run against the harness-backed Think in
\`src/harness/think.ts\` instead of \`src/think.ts\`. When every test passes,
Think moves onto \`agents/harness/think\`.

Some files test modules Think uses (extensions, fetch tools, messenger
helpers) rather than the \`Think\` class, so they pass either way. A failing
test that reaches a Think feature the harness-backed class does not have yet
fails with "Think.<name> is not supported by the harness-backed Think yet".

**${scoreboard.passed} of ${scoreboard.total} tests pass (${percent(scoreboard.passed, scoreboard.total)}).**

| File | Passing | |
| --- | --- | --- |
${rows.join("\n")}
`
);
spawnSync("pnpm", ["exec", "oxfmt", scoreboardMd, scoreboardJson], {
  cwd: packageDir,
  stdio: "ignore"
});
console.log("Wrote harness-compat.md and harness-compat.json.");
