/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 0c7a0b9cd271ea0b3f15464ff744e4c9)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  Assistant: DurableObjectNamespace<import("./src/server").Assistant>;
  CatalogMcp: DurableObjectNamespace<import("./src/server").CatalogMcp>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Assistant" | "CatalogMcp";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
