/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=tests/wrangler.jsonc --include-runtime=false tests/env.d.ts` (hash: 0f7448230f08649bd5c06f08a46a7c47)
interface __BaseEnv_Env {
  SENT_EMAILS: KVNamespace;
  GREETING_DO: DurableObjectNamespace<
    import("./test-main").GreetingDurableObject
  >;
  TRACER_BULLET_DO: DurableObjectNamespace<
    import("./test-main").TracerBulletDurableObject
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./test-main");
    durableNamespaces: "GreetingDurableObject" | "TracerBulletDurableObject";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
