/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=tests/wrangler.jsonc --include-runtime=false tests/env.d.ts` (hash: bac500a59831ca8356ed7b022b80da34)
interface __BaseEnv_Env {
  GREETING_DO: DurableObjectNamespace<
    import("./test-main").GreetingDurableObject
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./test-main");
    durableNamespaces: "GreetingDurableObject";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
