/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 6cd84da6ee208270e4f3bfdc921c94da)
interface __BaseEnv_Env {
  ARTIFACTS: Artifacts;
  LOADER: WorkerLoader;
  AI: Ai;
  MODEL_OVERRIDE: "";
  ARTIFACTS_REPO_PREFIX: "exo-prod";
  AUTH_MODE: "access";
  ACCESS_TEAM_DOMAIN: "";
  ACCESS_AUD: "";
  DEVELOPMENT_ACCESS_SUBJECT: "";
  DEVELOPMENT_ACCESS_EMAIL: "";
  ExoKernel: DurableObjectNamespace<import("./src/server").ExoKernel>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ExoKernel";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "MODEL_OVERRIDE"
      | "ARTIFACTS_REPO_PREFIX"
      | "AUTH_MODE"
      | "ACCESS_TEAM_DOMAIN"
      | "ACCESS_AUD"
      | "DEVELOPMENT_ACCESS_SUBJECT"
      | "DEVELOPMENT_ACCESS_EMAIL"
    >
  > {}
}
