/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 4b3f96ec72215ca1c638e969a26265f3)
interface __BaseEnv_Env {
  ARTIFACTS: Artifacts;
  LOADER: WorkerLoader;
  AI: Ai;
  MODEL_OVERRIDE: "";
  ARTIFACTS_REPO_PREFIX: "exo-prod";
  AUTH_MODE: "access";
  ACCESS_TEAM_DOMAIN: "https://agents-b8a.cloudflareaccess.com";
  ACCESS_AUD: "1cf54107d8ab7674caca49494009351ffced88698cfab01b968a691a0c3c1b67";
  DEVELOPMENT_ACCESS_SUBJECT: "";
  DEVELOPMENT_ACCESS_EMAIL: "";
  ExoKernel: DurableObjectNamespace<import("./src/server").ExoKernel>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ExoKernel";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "MODEL_OVERRIDE"
      | "ARTIFACTS_REPO_PREFIX"
      | "AUTH_MODE"
      | "ACCESS_TEAM_DOMAIN"
      | "ACCESS_AUD"
      | "DEVELOPMENT_ACCESS_SUBJECT"
      | "DEVELOPMENT_ACCESS_EMAIL"
    >
  > {}
}
