/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 37c65dec5822dfb4ab42fd8af2f2f257)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  MODEL_OVERRIDE: "";
  ExoKernel: DurableObjectNamespace<import("./src/server").ExoKernel>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ExoKernel";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "MODEL_OVERRIDE">
  > {}
}
