/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: e49893e2528d9c72b2c06a025073e7ab)
interface __BaseEnv_Env {
  COORDINATOR: DurableObjectNamespace<import("./src/index").CoordinatorAgent>;
  SPECIALIST: DurableObjectNamespace<import("./src/index").SpecialistAgent>;
  COORDINATOR_TASK_WORKFLOW: Workflow<
    Parameters<import("./src/index").CoordinatorWorkflow["run"]>[0]["payload"]
  >;
  SPECIALIST_TASK_WORKFLOW: Workflow<
    Parameters<import("./src/index").SpecialistWorkflow["run"]>[0]["payload"]
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "CoordinatorAgent" | "SpecialistAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
