/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 4901cbe7ec9f3ac61da08329908dcca1)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  AI: Ai;
  OpenCodeAgent: DurableObjectNamespace<import("./src/server").OpenCodeAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "OpenCodeAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
