/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 122dee341d88cfe61b7d065a6202d588)
interface __BaseEnv_Env {
  OpenCodeAgent: DurableObjectNamespace<import("./src/server").OpenCodeAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "OpenCodeAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
