/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 5429822d063d074a7921240208226b5f)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ThinkAgent";
  }
  interface Env {
    ThinkAgent: DurableObjectNamespace<import("./src/server").ThinkAgent>;
  }
}
interface Env extends Cloudflare.Env {}
