/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 38cbe3b231e56db244308761862d8136)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ThinkAgent" | "Workspace";
  }
  interface Env {
    WORKSPACE_FILES: R2Bucket;
    AI: Ai;
    ThinkAgent: DurableObjectNamespace<import("./src/server").ThinkAgent>;
    Workspace: DurableObjectNamespace<import("./src/server").Workspace>;
  }
}
interface Env extends Cloudflare.Env {}
