/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 95c701f09c72e7320a4900135bbfe8dc)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ThinkAgent";
  }
  interface Env {
    WORKSPACE_FILES: R2Bucket;
    AI: Ai;
    ThinkAgent: DurableObjectNamespace<import("./src/server").ThinkAgent>;
  }
}
interface Env extends Cloudflare.Env {}
