/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 3a793dda210c6964a4416951da2d49f2)
interface __BaseEnv_Env {
  CHANNEL_GATEWAY: DurableObjectNamespace<
    import("./src/server").ChannelGateway
  >;
  FAKE_AGENT: DurableObjectNamespace<import("./src/server").FakeAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ChannelGateway" | "FakeAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
