/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "QAAgent";
  }
  interface Env {
    LOADER: WorkerLoader;
    BROWSER: Fetcher;
    AI: Ai;
    QAAgent: DurableObjectNamespace<import("./src/server").QAAgent>;
  }
}
interface Env extends Cloudflare.Env {}
