/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: f72c7118f79b3a195d72b5347a725542)
interface __BaseEnv_Env {
  AI: Ai;
  AiSdkAgent: DurableObjectNamespace<import("./src/server").AiSdkAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "AiSdkAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
