/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 02058749c63b605f7cf60262acbc1c20)
interface __BaseEnv_Env {
  AI: Ai;
  ThinkAgent: DurableObjectNamespace<import("./src/server").ThinkAgent>;
  PiAgent: DurableObjectNamespace<import("./src/server").PiAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PiAgent" | "ThinkAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
