/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: c9ff3bbb7bc8571b030c0cb825c1fe14)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "DeepAgent";
  }
  interface Env {
    TAVILY_API_KEY: string;
    OPENAI_API_KEY: string;
    CF_API_TOKEN: string;
    DEEP_AGENT: DurableObjectNamespace<import("./src/index").DeepAgent>;
  }
}
interface Env extends Cloudflare.Env {}
