/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 08c590259158ab850063a462b6c4da65)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "AgentThread";
  }
  interface Env {
    TAVILY_API_KEY: string;
    OPENAI_API_KEY: string;
    AGENT_THREAD: DurableObjectNamespace<import("./src/index").AgentThread>;
  }
}
interface Env extends Cloudflare.Env {}
