/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 76e35a77e9b56d3cd663c33e4a37a572)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "DeepAgent";
  }
  interface Env {
    TAVILY_API_KEY: string;
    OPENAI_API_KEY: string;
    DEEP_AGENT: DurableObjectNamespace<import("./src/index").DeepAgent>;
  }
}
interface Env extends Cloudflare.Env {}
