/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: e7b6075f4de8ae2c761233ec8a7839f3)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ChessGame";
  }
  interface Env {
    HOST: "http://localhost:5174/";
    CHESS: DurableObjectNamespace<import("./src/index").ChessGame>;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HOST">> {}
}
