/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 460e117ebdafa9a9e343cc02572c1938)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  CodemodeMcp: DurableObjectNamespace<import("./src/index").CodemodeMcp>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "CodemodeMcp";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
