/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 94d1687f592f0bb5cbcd056355820198)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "RealtimeVoiceAgent";
  }
  interface Env {
    ACCOUNT_ID: "";
    API_TOKEN: "";
    REALTIME_VOICE_AGENT: DurableObjectNamespace<
      import("./src/index").RealtimeVoiceAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "ACCOUNT_ID" | "API_TOKEN">> {}
}
