/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: auto-regenerable)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Assistant" | "Researcher";
  }
  interface Env {
    AI: Ai;
    // `Assistant` is the only top-level DO binding. `Researcher` is a
    // facet of Assistant — reached via `this.subAgent(Researcher, id)`
    // inside Assistant. `Researcher` still needs to live in
    // `new_sqlite_classes` so the runtime knows how to construct it,
    // but not as a namespace binding.
    Assistant: DurableObjectNamespace<import("./src/server").Assistant>;
  }
}
interface Env extends Cloudflare.Env {}
