/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 2a1e273a47e3a7474947cfe52ad61221)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Inbox" | "Chat";
  }
  interface Env {
    AI: Ai;
    Inbox: DurableObjectNamespace<import("./src/server").Inbox>;
    Chat: DurableObjectNamespace<import("./src/server").Chat>;
  }
}
interface Env extends Cloudflare.Env {}
