/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: auto-regenerable)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Inbox" | "Chat";
  }
  interface Env {
    AI: Ai;
    // `Inbox` is the only top-level DO binding. `Chat` is a facet of
    // Inbox — reached via `this.subAgent(Chat, id)` inside Inbox, or
    // via `/agents/inbox/{user}/sub/chat/{id}` from a client. `Chat`
    // still needs to live in `new_sqlite_classes` so the runtime
    // knows how to construct it, but not as a namespace binding.
    Inbox: DurableObjectNamespace<import("./src/server").Inbox>;
  }
}
interface Env extends Cloudflare.Env {}
