/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 9eb7c95ec300c6e6a8c9fb23e831da13)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "PayAgent";
  }
  interface Env {
    SERVER_ADDRESS: "0xFa75d8F07BA244c29cbdb32fD3093D759857072E";
    PAY_AGENT: DurableObjectNamespace<import("./src/index").PayAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "SERVER_ADDRESS">
  > {}
}
