/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 73476bee4c48af09b1c96a69e41e7a79)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ChatAgent" | "Sandbox";
  }
  interface Env {
    AI: Ai;
    ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
    Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
  }
}
interface Env extends Cloudflare.Env {
  ANTHROPIC_API_KEY: string;
}
