// Generated by `pnpm types`; kept minimal by hand for the demo.
interface Env {
  AI: Ai;
  HostedAgent: DurableObjectNamespace<import("./src/server").HostedAgent>;
  CHAT_STATE: DurableObjectNamespace<
    import("chat-state-cloudflare-do").ChatStateDO
  >;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET_TOKEN: string;
  TELEGRAM_BOT_USERNAME?: string;
}
