/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 4210c5187c4aad2dc19d10b6cd1859a6)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  BROWSER: BrowserRun;
  AI: Ai;
  PiAgent: DurableObjectNamespace<import("./src/server").PiAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PiAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
