name: Publish to pkg.pr.new for pre-release

on:
  pull_request: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(jq -r '.packages["node_modules/playwright"].version' package-lock.json)" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Publish agents package to pkg.pr.new
        run: npx pkg-pr-new publish ./packages/agents
