name: Prerelease

on:
  push:
    branches:
      - main

jobs:
  prerelease:
    if: ${{ github.repository_owner == 'cloudflare' }}
    timeout-minutes: 10
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(npm list --json playwright | jq -r '.dependencies.playwright.version')" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

      - run: npm ci

      - name: Modify package.json version
        run: npx tsx .github/version-script.ts

      - name: Resolve workspace dependencies
        run: npx tsx .github/resolve-workspace-versions.ts

      - run: npm run build
      - run: npm run check
      - run: CI=true npm run test

      - run: npm publish --tag beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/agents

      - run: npm publish --tag beta
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/hono-agents
