/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 61f6f80bcabdb242302132dffe1290a3)
interface __BaseEnv_Env {
  EMAIL: SendEmail;
  AI: Ai;
  EMAIL_FROM: "agent@example.com";
  SUPPORT_EMAIL: "support@example.com";
  TELEGRAM_SUPPORT_CHAT_ID: "123456789";
  PUBLIC_BASE_URL: "http://localhost:8787";
  OPERATIONS_WEBHOOK_URL: "http://localhost:8787/operations-webhook";
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_WEBHOOK_SECRET: string;
  CHANNELS_EXAMPLE: DurableObjectNamespace<
    import("./src/index").ChannelsExample
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "ChannelsExample";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "EMAIL_FROM"
      | "SUPPORT_EMAIL"
      | "TELEGRAM_SUPPORT_CHAT_ID"
      | "PUBLIC_BASE_URL"
      | "OPERATIONS_WEBHOOK_URL"
      | "TELEGRAM_BOT_TOKEN"
      | "TELEGRAM_WEBHOOK_SECRET"
    >
  > {}
}
