/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts`
interface __BaseEnv_Env {
  HubObject: DurableObjectNamespace<import("./src/index").HubObject>;
  NoteAgent: DurableObjectNamespace<import("./src/index").NoteAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "HubObject" | "NoteAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
